openapi: 3.0.1
info:
  title: Peakflo API
  description: 'The Peakflo API follows REST. Our APIs are organised as resource-oriented URLs, returns JSON responses.  They return standard HTTP response codes. You will need a JWT token to access the resources you are authorized to. '
  contact:
    url: 'https://peakflo.co/'
    email: info@peakflo.co
  x-logo:
    url: 'https://assets.dorik.com/5fa7a91326674600114e7aca/images/logo_black_zv0e3kxb.png'
    altText: Peakflo logo
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  url: 'https://docs.peakflo.co'
servers:
  - url: api.peakflo.co/v1
    description: Production
  - description: Staging
    url: stage-api.peakflo.co/v1
security:
  - bearerAuth: []
tags:
  - name: Customers
    description: The customer
  - name: Contacts
    description: The customers contact
  - name: Invoices
    description: The customers invoices
  - name: Payments
    description: The customers payments
  - name: Credit Notes
    description: The customers credit notes
paths:
  /customers:
    post:
      tags:
        - Customers
      summary: Add a customer
      description: Add a new customer
      operationId: add-customer
      requestBody:
        description: Customer to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
            examples:
              Example:
                value:
                  companyName: Mc win pte ltd
                  externalId: 1245a32
                  currency: USD
                  status: active
                  parentCompanyId: 23oc2344
                  accountManagerEmail: johndoe@peakflo.co
                  pauseWorkflow: false
                  contact:
                    - externalId: 234wf33
                      firstName: Peter
                      lastName: Wong
                      email: peterwong@mcwin.com
                      phone: '6591234567'
                      isMainContact: false
        required: false
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
              examples:
                Example:
                  value:
                    companyName: Mc win pte ltd
                    externalId: 1245a32
                    currency: USD
                    status: active
                    parentCompanyId: 23oc2344
                    accountManagerEmail: johndoe@peakflo.co
                    pauseWorkflow: false
                    contact:
                      - externalId: 234wf33
                        firstName: Peter
                        lastName: Wong
                        email: peterwong@mcwin.com
                        phone: '6591234567'
                        isMainContact: false
        '400':
          description: Bad request
          content: {}
        '409':
          description: Conflict
          content: {}
      x-codegen-request-body-name: Customer
    parameters: []
  '/customers/{customerExternalId}':
    put:
      tags:
        - Customers
      summary: 'Update a customer '
      description: Update an existing customer. Any field not provided will be left unchanged
      operationId: update-customer
      requestBody:
        description: Customer to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
            examples:
              Example:
                value:
                  companyName: Mc win pte ltd
                  externalId: 1245a32
                  currency: USD
                  status: active
                  parentCompanyId: 23oc2344
                  accountManagerEmail: johndoe@peakflo.co
                  pauseWorkflow: false
        required: false
      responses:
        '200':
          description: Updated customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
              examples:
                Example:
                  value:
                    companyName: Mc win pte ltd
                    externalId: 1245a32
                    currency: USD
                    status: active
                    parentCompanyId: 23oc2344
                    accountManagerEmail: johndoe@peakflo.co
                    pauseWorkflow: false
                    contact:
                      - externalId: 234wf33
                        firstName: Peter
                        lastName: Wong
                        email: peterwong@mcwin.com
                        phone: '6591234567'
                        isMainContact: false
        '404':
          description: Not Found
        '409':
          description: Conflict
          content: {}
      x-codegen-request-body-name: Customer
    delete:
      tags:
        - Customers
      summary: Delete a customer
      operationId: delete-customer
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      description: Delete a customer
    parameters:
      - schema:
          type: string
        name: customerExternalId
        in: path
        required: true
  '/customers/{customerExternalId}/contacts':
    post:
      summary: Add a contact
      tags:
        - Contacts
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
              examples:
                Example:
                  value:
                    externalId: 234wf33
                    firstName: Peter
                    lastName: Wong
                    email: peterwong@mcwin.com
                    phone: '6591234567'
                    isMainContact: false
        '400':
          description: 'Bad Request '
        '409':
          description: Conflict
      operationId: add-contact
      description: Add a contact to existing customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
            examples:
              Example:
                value:
                  externalId: 234wf33
                  firstName: Peter
                  lastName: Wong
                  email: peterwong@mcwin.com
                  phone: '6591234567'
                  isMainContact: false
        description: Contact to add
    parameters:
      - schema:
          type: string
        name: customerExternalId
        in: path
        required: true
        description: The customer external Id
  '/customers/{customerExternalId}/contacts/{contactExternalId}':
    parameters:
      - schema:
          type: string
        name: customerExternalId
        in: path
        required: true
        description: The customer external Id
      - schema:
          type: string
        name: contactExternalId
        in: path
        required: true
        description: The contact external Id
    put:
      summary: Update a contact
      tags:
        - Contacts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
              examples:
                Example:
                  value:
                    externalId: 234wf33
                    firstName: Peter
                    lastName: Wong
                    email: peterwong@mcwin.com
                    phone: '6591234567'
                    isMainContact: false
        '404':
          description: Not Found
        '409':
          description: Conflict
      operationId: update-contact
      description: Update a contact
    delete:
      summary: Delete a contact
      tags:
        - Contacts
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      operationId: delete-contact
      description: Delete a contact
  /invoices:
    post:
      summary: Add an invoice
      operationId: add-invoice
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '409':
          description: Conflict
      description: Add a new invoice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
        description: The invoice to be added
      tags:
        - Invoices
    parameters: []
  '/invoices/{invoiceExternalId}':
    parameters:
      - schema:
          type: string
        name: invoiceExternalId
        in: path
        required: true
        description: The invoice external Id
    put:
      summary: Update an invoice
      operationId: update-invoice
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
        '404':
          description: Not Found
        '409':
          description: Conflict
      description: Update an invoice. Any field not provided will be left unchanged.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
            examples: {}
        description: The invoice to update
      tags:
        - Invoices
    delete:
      tags:
        - Invoices
      summary: Delete an invoice
      operationId: delete-invoice
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      description: Delete an invoice
  '/invoices/{invoiceExternalId}/attachments':
    parameters:
      - schema:
          type: string
        name: invoiceExternalId
        in: path
        required: true
        description: The invoice external Id
    put:
      summary: Add an attachment to invoice
      operationId: add-attachment
      responses:
        '200':
          description: OK
      tags:
        - Invoices
      description: Add an attachment to invoice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Attachment'
  /creditnotes:
    post:
      tags:
        - Credit Notes
      summary: Add a credit note
      operationId: add-creditnotes
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditNote'
        '400':
          description: Bad Request
        '409':
          description: Conflict
      description: Add a credit note
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditNote'
        description: The credit note to add
  '/creditnotes/{creditNoteExternalId}':
    parameters:
      - schema:
          type: string
        name: creditNoteExternalId
        in: path
        required: true
        description: The credit note external Id
    put:
      tags:
        - Credit Notes
      summary: Update a credit note
      operationId: update-creditnote
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditNote'
        '404':
          description: Not Found
        '409':
          description: Conflict
      description: Update a credit note
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditNote'
        description: The credit note to update
    delete:
      summary: Delete a credit note
      operationId: delete-creditnote
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      tags:
        - Credit Notes
      description: Remove a credit note
  /payments:
    post:
      summary: Add a payment
      operationId: add-payment
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '400':
          description: Bad Request
        '409':
          description: Conflict
      tags:
        - Payments
      description: Add a payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
        description: The payment to add
  '/payments/{paymentExternalId}':
    parameters:
      - schema:
          type: string
        name: paymentExternalId
        in: path
        required: true
        description: The payment external Id
    put:
      summary: Update a payment
      operationId: update-payment
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '409':
          description: Conflict
      tags:
        - Payments
      description: Update a payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
        description: The payment to update
    delete:
      summary: Delete a payment
      operationId: delete-payment
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      tags:
        - Payments
      description: Delete a payment
components:
  schemas:
    Customer:
      type: object
      x-examples:
        Example:
          companyName: string
          externalId: string
          currency: USD
          status: active
          parentCompanyId: string
          accountManagerEmail: string
          registrationNumber: string
          taxNumber: string
          notes: string
          pauseWorkflow: true
          contact:
            - firstName: string
              lastName: string
              middleName: string
              email: johndoe@peakflo.co
              phone: '6591234567'
              isMainContact: false
      description: The customer model
      properties:
        externalId:
          type: string
          description: The external Id of the company
        companyName:
          type: string
          description: The company name
        currency:
          type: string
          description: The customers currency. Must be a ISO 4217 code
        status:
          type: string
          description: The status of the company
          enum:
            - unknow
            - active
            - archived
          example: active
        accountManagerEmail:
          type: string
          description: The account manager email
        registrationNumber:
          type: string
          description: The company registration number
        taxNumber:
          type: string
          description: The company tax number
        notes:
          type: string
          description: Notes
        pauseWorkflow:
          type: boolean
          description: Indicate whether workflow is paused for this company or not. If paused then no actions will take place.
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
        statementFile:
          type: string
          description: The statement file
        addresses:
          type: array
          description: The customers addresses
          items:
            $ref: '#/components/schemas/Address'
      required:
        - externalId
        - companyName
        - currency
        - status
    Contact:
      type: object
      description: The contact model
      properties:
        externalId:
          type: string
          description: The external Id for the contact
        firstName:
          type: string
          description: The first name of the contact
        lastName:
          type: string
          description: The last name of the contact
        middleName:
          type: string
          description: The middle name of the contact
        email:
          type: string
          description: The email Id of the contact
          example: johndoe@peakflo.co
        phone:
          type: string
          description: The phone number of the contact along with country code
          example: '6591234567'
        isMainContact:
          type: boolean
          description: Indicate if this is the main contact.
          default: false
        title:
          type: string
          description: The title
          example: Dr.
        position:
          type: string
          enum:
            - Sales
            - Accounting
            - Management
            - Unknown
          example: Sales
          description: The postion of the contact in the company
        description:
          type: string
          description: Description about contact
        suffix:
          type: string
        altPhone:
          type: string
          description: Alternate phone number
      required:
        - externalId
        - firstName
        - lastName
        - email
    LineItem:
      description: The line item
      type: object
      properties:
        itemName:
          type: string
          description: The item name
        description:
          type: string
          description: Description about line item
        unitAmount:
          type: number
          description: Amount per unit for the line item
        quantity:
          type: number
          description: 'Number of units '
        discountAmount:
          type: number
          description: Discount on total amount
        subTotal:
          type: number
          description: The Subtotal
        taxAmount:
          type: number
          description: The tax amount
        totalAmount:
          type: number
          description: The total amount
        itemRef:
          type: string
          description: 'Reference to the product, service type, or inventory item, to which the line item is linked.'
      required:
        - itemName
        - description
        - unitAmount
        - quantity
        - totalAmount
    Attachment:
      description: The attachment
      type: object
      properties:
        externalId:
          type: string
          description: The external Id for the attachment
        name:
          type: string
          description: 'Name of the attachment '
        dateCreated:
          type: string
          description: The date at which the attachment created. Follow ISO 8601 format
        contentType:
          type: string
          description: Content type of attachment
        data:
          type: string
          description: Data in base 64 format
        fileType:
          $ref: '#/components/schemas/FileType'
      required:
        - externalId
        - name
        - contentType
        - data
    FileType:
      title: FileType
      type: string
      enum:
        - cabinet
        - invoice
        - statement
        - transaction
        - other
      description: The supported file types
      x-examples:
        Example: Invoice
    Invoice:
      description: ''
      type: object
      properties:
        externalId:
          type: string
          description: The external Id of the invoice
        customerRef:
          type: string
          description: The customer Ref or Id
        issueDate:
          type: string
          description: Invoice issue date. Follow ISO8601 format
          example: '2021-04-28T12:30:00'
        dueDate:
          type: string
          description: The invoice due date. Follow ISO8601 format
        totalAmount:
          type: number
          description: The total invoice amount
        currency:
          type: string
          description: The invoice currency. Follow ISO 4217 code
        invoiceNumber:
          type: string
          description: The invoice number
        modifiedDate:
          type: string
          description: The invoice modified date. Follow ISO8601 format
        paidOnDate:
          description: The invoice paid date. Follow ISO8601 format
          type: string
        currencyRate:
          type: number
          description: The currency conversion rate to be applied to all the amount fields when converting to base currency
        lineItems:
          type: array
          uniqueItems: true
          description: The invoice line items
          items:
            $ref: '#/components/schemas/LineItem'
        totalDiscount:
          type: number
          description: Discount on invoice total amount
        totalTaxAmount:
          type: number
          description: Total tax amount on invoice
        amountDue:
          type: number
          description: Amount due on invoice
        status:
          type: string
          enum:
            - Draft
            - Submitted
            - PartiallyPaid
            - Void
            - Paid
            - Open
          example: Paid
          default: Draft
          description: The invoice status
        note:
          type: string
          description: Notes about invoice
        attachments:
          type: array
          uniqueItems: true
          description: The invoice attachments
          items:
            $ref: '#/components/schemas/Attachment'
        expectedPaymentDate:
          type: string
          description: The expected payment date. Follow ISO8601 format
        allocatedOnDate:
          type: string
          description: The allocated date. Follow ISO8601 format
        subTotal:
          type: number
          description: The sub total
      required:
        - externalId
        - itemName
        - customerRef
        - issueDate
        - dueDate
        - totalAmount
        - currency
        - invoiceNumber
    Address:
      description: The customers address
      type: object
      properties:
        type:
          type: string
          description: The address type
        line1:
          type: string
          description: The address line 1
        line2:
          type: string
        city:
          type: string
          description: The city
        region:
          type: string
          description: The region
        country:
          type: string
          description: The country
        postalCode:
          type: string
          description: The postal code
      required:
        - line1
        - city
        - country
        - postalCode
    CreditNote:
      description: ''
      type: object
      properties:
        externalId:
          type: string
          description: The externalId for the credit note
        creditNoteNumber:
          type: string
          description: Human readable form of credit note
        customerRef:
          type: string
          description: The customer Id
        totalAmount:
          type: number
          description: The total amount
        totalDiscount:
          type: number
          description: The total discount
        subTotal:
          type: number
          description: The subtotal
        totalTaxAmount:
          type: number
          description: The total tax amount
        remainingCredit:
          type: number
          description: The remaining credit amount
        status:
          type: string
          enum:
            - Draft
            - Submitted
            - PartiallyPaid
            - Void
            - Paid
          default: Draft
          example: Paid
          description: The status of credit note
        issueDate:
          type: string
          description: The issue date. Follow ISO8601 format
        allocatedOnDate:
          type: string
          description: The credit note allocated date. Follow ISO8601 format
        currency:
          type: string
          description: The credit note currency. Follow ISO 4217 code
        currencyRate:
          type: number
          description: The currency conversion rate to be applied to all the amount fields when converting to base currency
        lineItems:
          type: array
          items:
            $ref: '#/components/schemas/LineItem'
        modifiedDate:
          type: string
          description: Credit note last modified date. Follow ISO8601 format
        note:
          type: string
      required:
        - externalId
        - creditNoteNumber
        - customerRef
        - totalAmount
        - remainingCredit
        - issueDate
        - currency
    Payment:
      description: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
          description: The unique paymentId
        customerRef:
          type: string
          minLength: 1
          description: The customer Id
        totalAmount:
          type: number
          description: Total amount
        remainingAmount:
          type: number
          description: The amount that is not paid yet
        currency:
          type: string
          minLength: 1
          description: The currency of payment
        currencyRate:
          description: The currency conversion rate to be applied to all the amount fields when converting to base currency
          type: number
        date:
          type: string
          minLength: 1
          description: The payment date.Follow ISO8601 format
        paymentLines:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: '#/components/schemas/PaymentLine'
        modifiedDate:
          type: string
          minLength: 1
          description: Date the record was last changed
        reference:
          type: string
          minLength: 1
        note:
          type: string
          minLength: 1
          description: Notes related to this payment
      required:
        - id
        - customerRef
        - totalAmount
        - remainingAmount
        - currency
        - date
        - modifiedDate
        - reference
    PaymentLine:
      description: The payment line
      type: object
      properties:
        amount:
          type: number
          description: |-
            Amount by which the balance of the linked entity is altered, in the currency of the linked entity.
            A negative link amount reduces the outstanding amount on the accounts receivable account.
            A positive link amount increases the outstanding amount on the accounts receivable account.
        type:
          type: string
          description: Type of payment
          enum:
            - Invoice
            - Refund
          default: Invoice
          example: Invoice
        id:
          type: string
          description: Reference to the item to which the payment is made
          example: Invoice Id if this is a invoice type payment
        currencyRate:
          type: number
          description: The currency conversion rate to be applied to all the amount fields when converting to base currency
      required:
        - amount
        - type
        - id
        - currencyRate
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters: {}
